POST http://localhost:3000/registerESP/beacon 
Content-Type: application/json

{
  "posicao": "Está na sala",
  "MACAddress": "F4:12:FA:E2:3E:94",
  "name": "Matema"
}

### 


POST https://yuzr0k-3000.preview.csb.app/registerESP/tags 
Content-Type: application/json

{
  "RFID": "3343",
  "posicao": "Está na sala",
  "MACAddress": "F4:12:FA:E2:3E:94",
  "name": "tag1"
}

###

POST https://localhost:3000/beacon/edit-existing
Content-Type: application/json

{
  "AreaID"
}