POST http://localhost:3000/registerESP/beacon 
Content-Type: application/json

{
  "posicao": "Está na sala",
  "MACAddress": "F4:12:FA:E2:3E:94",
  "name": "Matema"
}

### 


POST https://6qwj4p-3000.preview.csb.app/registerESP/tags 
Content-Type: application/json

{
  "RFID": "3343",
  "posicao": "Está na sala",
  "MACAddress": "F4:12:FA:E2:3E:94",
  "name": "tag1"
}

###

POST http://localhost:3000/beacon/edit-existing
Content-Type: application/json

{
  "AreaID"
}

###

POST http://localhost:3000/registerESP/tags 
Content-Type: application/json

{
  "position": "In",
  "area_ID": 42, 
  "user_ID": 1234,
  "MACAddress": "F4:12:FA:E2:3E:94",
  "name": "tag1"
}

###

GET http://localhost:3000/registerESP/beacon